# Generated by Django 6.1 on 2026-09-11 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('researching', 'Researching'), ('applied', 'Applied'), ('in_review', 'In Review'), ('approved', 'Approved'), ('denied', 'Denied')], default='researching', max_length=20)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_for', models.DateTimeField()),
                ('facility_name', models.CharField(blank=True, default='', max_length=200)),
                ('facility_address', models.CharField(blank=True, default='', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tracker.claim')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
